"""
File for getting a peek of the structure of output generated by the LLM to differentiate how we can cut the output into text and code block
"""

import config
from src.llm import chat
from src.trace import Run

prompt = (config.ROOT / "prompts" / "step1_baseline.txt").read_text(encoding="utf-8")
run = Run("peek")
answer = chat(run, [{"role": "user", "content": prompt + "\n/no_think"}], label="peek")

print("=" * 60)
print(answer)
print("=" * 60)
print(f"length: {len(answer)} characters")